export default {
  type: "object",
  required: [
    "type",
    "attendees",
    "master_trainer",
    "start_date",
    "start_time",
    "end_date",
    "end_time",
    "reminders",
    "location",
    "location_type",
  ],
  properties: {
    type: {
      icons: "VidiconLine",
      type: "string",
      label: "Event Type",
      format: "select",
      enum: [
        "Prerak Orientation",
        "Prerak FLN Training",
        "Prerak Camp Execution Training",
      ],
    },
    name: {
      icons: "UserFollowLineIcon",
      label: "Event Name \n (Batch Number)",
      title: "Event Name (Batch Number)",
      type: "string",
    },
    master_trainer: {
      icons: "UserFollowLineIcon",
      label: "Master Trainer",
      title: "Master Trainer",
      type: "string",
    },
    attendees: {
      name: "UserFollowLineIcon",
      label: "Select Candidates",
      title: "Select Candidates",
      type: ["string", "array"],
    },
    start_date: {
      icons: "CalendarLineIcon",
      label: "Start Date",
      title: "Start Date",
      type: "string",
      format: "alt-date",
    },
    start_time: {
      icons: "TimeLineIcon",
      label: "Start Time",
      title: "Start time",
      type: "string",
      format: "string",
    },
    end_date: {
      icons: "CalendarLineIcon",
      label: "End Date",
      title: "End Date",
      type: "string",
      format: "alt-date",
    },
    end_time: {
      icons: "TimeLineIcon",
      label: "End time",
      title: "End time",
      type: "string",
      format: "string",
    },
    reminders: {
      icons: "Notification2LineIcon",
      label: "Reminder",
      type: "array",
      title: "Reminder",
      items: {
        type: "string",
      },
      uniqueItems: true,
    },
    location: {
      icons: "MapPinLineIcon",
      label: "Location",
      title: "Location",
      type: "string",
    },
    location_type: {
      icons: "MapPinLineIcon",
      label: "Location Type",
      title: "Location Type",
      type: "string",
      format: "CustomR",
      enumNames: ["online", "offline"],
      enum: ["online", "offline"],
    },
  },
};
