export default {
  type: "object",
  required: [
    "type",
    "attendees",
    "name",
    "master_trainer",
    "start_date",
    // "start_time",
    "end_date",
    // "end_time",
    "reminders",
    "location",
    "location_type",
  ],
  properties: {
    type: {
      icons: "VidiconLineIcon",
      type: "string",
      label: "EVENT_TYPE",
      format: "select",
    },
    name: {
      icons: "UserFollowLineIcon",
      label: "EVENT_NAME",
      title: "EVENT_NAME",
      type: "string",
    },
    master_trainer: {
      icons: "UserFollowLineIcon",
      label: "MASTER_TRAINER",
      title: "MASTER_TRAINER",
      type: "string",
    },
    attendees: {
      name: "UserFollowLineIcon",
      label: "Select Candidates",
      title: "Select Candidates",
      type: ["string", "array"],
    },
    start_date: {
      icons: "CalendarLineIcon",
      label: "EVENT_START_DATE_TIME",
      title: "Start Date & Time",
      type: "string",
      format: "alt-date",
    },
    start_time: {
      // icons: "TimeLineIcon",
      // label: "Start Time",
      // title: "Start time",
      type: "string",
      format: "string",
    },
    end_date: {
      icons: "CalendarLineIcon",
      label: "EVENT_END_DATE_TIME",
      title: "End Date & Time",
      type: "string",
      format: "alt-date",
    },
    end_time: {
      // icons: "TimeLineIcon",
      // label: "End time",
      // title: "End time",
      type: "string",
      format: "string",
    },
    reminders: {
      icons: "Notification2LineIcon",
      label: "REMINDER",
      type: "array",
      title: "Reminder",
      items: {
        type: "string",
      },
      uniqueItems: true,
    },
    location: {
      icons: "MapPinLineIcon",
      label: "LOCATION",
      title: "LOCATION",
      type: "string",
    },
    location_type: {
      icons: "MapPinLineIcon",
      label: "LOCATION_TYPE",
      title: "Location Type",
      type: "string",
      format: "CustomR",
      enumNames: ["ONLINE", "OFFLINE"],
      enum: ["online", "offline"],
    },
  },
};
