name: Cleanup old pre releases
on: 
  push: 
    tags:
       - v[0-9]+.[0-9]+.[0-9]+beta.[0-9]+             
       - v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+
       - 'v[0-9]+.[0-9]+.[0-9]+beta.[0-9]+'           
       - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

defaults:
  run:
    working-directory: .
    
jobs:
  build:
    name: Cleanup old pre releases
    environment: GLOBAL
    runs-on: ubuntu-latest
    steps:
      - name: List contents
        run: |
          ls -lha
          
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cleanup old pre releases
        uses: jay2610/delete-older-releases@1.4.0
        with:
          repo: tekdi/eg-website # defaults to current repo
          keep_latest: 5
          delete_tags: true
          #delete_tag_pattern: beta # defaults to ""
          delete_type: 'prerelease'
          #target_branch: 'master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
