name: Deploy to UAT
on: 
  push: 
    tags:
       - v[0-9]+.[0-9]+.[0-9]+beta.[0-9]+             
       - v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+
       - 'v[0-9]+.[0-9]+.[0-9]+beta.[0-9]+'           
       - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'
jobs:
  build:
    name: Generate Build and Deploy to UAT
    environment: QA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node Env
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
          
      - name: Generate React Build
        run: |
          yarn install
          yarn workspace @shiksha/common-lib build
          yarn install
          yarn build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          REACT_APP_BANNER_MESSAGE: ${{ secrets.REACT_APP_BANNER_MESSAGE }}
          REACT_APP_GA_MEASUREMENT_ID: ${{ vars.REACT_APP_GA_MEASUREMENT_ID }}
          REACT_APP_SENTRY_DSN_URL: ${{ secrets.REACT_APP_SENTRY_DSN_URL }}
          REACT_APP_SENTRY_ENV: ${{ secrets.REACT_APP_SENTRY_ENV }}
          REACT_APP_SCHOLARSHIP_URL: ${{ secrets.REACT_APP_SCHOLARSHIP_URL }}
          REACT_APP_SCHOLARSHIPS_BAP_ID: ${{ secrets.REACT_APP_SCHOLARSHIPS_BAP_ID }}
          REACT_APP_SCHOLARSHIPS_BAP_URI: ${{ secrets.REACT_APP_SCHOLARSHIPS_BAP_URI }}
          REACT_APP_SCHOLARSHIPS_BASE_URL: ${{ secrets.REACT_APP_SCHOLARSHIPS_BASE_URL }}
          REACT_APP_SCHOLARSHIP_DOMAIN: ${{ secrets.REACT_APP_SCHOLARSHIP_DOMAIN }}
          REACT_APP_SCHOLARSHIPS_INSERT_ORDER: ${{ secrets.REACT_APP_SCHOLARSHIPS_INSERT_ORDER }}
          REACT_APP_SCHOLARSHIP_DB_CACHE: ${{ secrets.REACT_APP_SCHOLARSHIP_DB_CACHE }}
          REACT_APP_JOBS_BAP_ID: ${{ secrets.REACT_APP_JOBS_BAP_ID }}
          REACT_APP_JOBS_BAP_URI: ${{ secrets.REACT_APP_JOBS_BAP_URI }}
          REACT_APP_JOBS_BASE_URL: ${{ secrets.REACT_APP_JOBS_BASE_URL }}
          REACT_APP_JOBS_DOMAIN: ${{ secrets.REACT_APP_JOBS_DOMAIN }}
          REACT_APP_JOBS_INSERT_ORDER: ${{ secrets.REACT_APP_JOBS_INSERT_ORDER }}
          REACT_APP_JOBS_DB_CACHE: ${{ secrets.REACT_APP_JOBS_DB_CACHE }}
          REACT_APP_LEARNINGS_BAP_ID: ${{ secrets.REACT_APP_LEARNINGS_BAP_ID }}
          REACT_APP_LEARNINGS_BAP_URI: ${{ secrets.REACT_APP_LEARNINGS_BAP_URI }}
          REACT_APP_LEARNINGS_BASE_URL: ${{ secrets.REACT_APP_LEARNINGS_BASE_URL }}
          REACT_APP_LEARNINGS_DB_CACHE: ${{ secrets.REACT_APP_LEARNINGS_DB_CACHE }}
          REACT_APP_LEARNINGS_DOMAIN: ${{ secrets.REACT_APP_LEARNINGS_DOMAIN }}
          
      - name: Create Lerna Bundles for Submodules
        run: |
          sh ./scripts/pack-prod-build.sh

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          
      - name: Add Entry to Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts
        
      - name: Copy Build Artifact using Rsync
        run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" eg-website.tar ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/eg-website.tar

      - name: Unzip Artifact to Correct Locations to Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            tar -xvf eg-website.tar -C /var/www/html/
            #cp eg-website.tar /var/www/html2
            #rm -rf *
            #cp ../eg-website.tar ./
            #tar -xvf eg-website.tar .

      - name: Notify on Slack channel
        uses: iRoachie/slack-github-actions@v2.3.2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
        if: ${{ always() }}
